#!/usr/bin/env python
import os
import sys
from optparse import OptionParser
from rdbtools import RdbParser, JSONCallback

def main():
    parser = OptionParser()
    
    usage = "usage: %prog [options] /path/to/dump.rdb"
    parser.add_option("-f", "--file", dest="output",
                  help="Output file", metavar="FILE")
    parser.add_option("-n", "--dbnum", dest="dbnum", default=0,
                  help="Database number. Defaults to 0")
    parser.add_option("-k", "--keys", dest="keys",
                  help="Keys to export. This can be a regular expression")
    
    (options, args) = parser.parse_args()
    
    if len(args) == 0:
        parser.error("Redis RDB file not specified")
    
    dump_file = args[0]
    if options.output:
        with open('/home/sri/apps/redis-rdb-tools/rdbtools/dump.json', "wb") as f:
            callback = JSONCallback(f)
            parser = RdbParser(callback)
            parser.parse(dump_file)
    else:
        callback = JSONCallback(sys.stdout)
        parser = RdbParser(callback)
        parser.parse(dump_file)
    
if __name__ == '__main__':
    main()

